on:
  push:
  workflow_dispatch:

jobs:
  helloworld:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo "Lecture CI/CD"
      - name: Get the present working directory
        run: pwd

      
      - name: list all the files
      
      - name: list all the files with details
        run: ls

      -name:Run the test
       run:/gradlew test --scan
